name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - README.md
      - .gitattributes
      - .gitignore
      - .gitpod.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - run: npx markdownlint-cli .
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.124.0"
          extended: true
      - name: Config Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Update Submodule
        run: |
          git submodule sync
          git submodule update --init --recursive
          git submodule update --remote
          if [[ `git status --porcelain` ]]; then
            echo Changes.
            git add .
            git commit -m "Update Submodule"
            git push
          else
            echo No Changes.
          fi
      - name: Build
        run: hugo --minify
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
